name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Deploy to Server
      uses: appleboy/ssh-action@master

      with:
          username: "obak"
          host: "104.161.20.171"
          password: "obak"
          script: 'cd DeployScripts/ && ./laravel-deploy.sh'  