name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: 2

    - name: Setup PHP
    
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e

      with:
          php-version: "7.4"

    # - name: Create .env file
    #   run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    # - name: Install Dependencies
    #   run: composer install      

    # - name: Set required directory permissions
    #   run: chmod -R 777 storage

    # - name: Generate key
    #   run: php artisan key:generate

    - name: Deploy to Server
      uses: appleboy/ssh-action@master

      with:
          username: "obak"
          host: "104.161.20.171"
          password: "obak"
          script: 'cd /var/www/html/VPS-Server-Laravel && ./deploy.sh'  
