name: Deploy Application

on:

  push:

    branches:
      - master

jobs:
  
  create-deployment-artifacts:

    name: Create deplyment artifacts

    runs-on: ubuntu-latest

  steps:

  - uses: actions/checkout@v2
