name: CD

on:

  push:

    branches: [ master ]

  pull_request:
      branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Deploy to production

      uses: appleboy/ssh-action@master

      # with:

      #   username: "obak"

      #   host: "104.161"

      #   password: "vps password"

      #   script: 'cd /var/www/html && ./deploy.sh'
