name: Deploy Application

on:
  push:
    branches: [ master ]



# // code from earlier is ommited for clearity

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v2
  
   - name: Compile CSS and Javascript
     run: |
      npm install
      npm run prod
